import streamlit as st
import pandas as pd

st.title("Higher Signal AI")

uploaded_file = st.file_uploader(
    "Upload Target Account CSV",
    type=["csv"]
)

if uploaded_file:
    df = pd.read_csv(uploaded_file, encoding="latin1")

    # Clean the CSV to remove export/footer metadata
    def clean_salesforce_csv(df):
        # Remove rows containing metadata keywords
        metadata_keywords = ["confidential info", "copyright", "generated by", "leandata", "export", "report"]
        
        # Convert all columns to string for checking
        df_str = df.astype(str)
        
        # Check each row for metadata keywords
        mask = ~df_str.apply(lambda row: row.str.contains('|'.join(metadata_keywords), case=False, na=False).any(), axis=1)
        df = df[mask]
        
        # Remove rows where Account Name, Website, and LinkedIn are mostly empty
        key_fields = ["Account Name", "Company", "Name", "Account", "Website", "LinkedIn", "Url"]
        existing_key_fields = [col for col in key_fields if col in df.columns]
        
        if existing_key_fields:
            # Check if key fields are empty or None
            df = df.dropna(subset=existing_key_fields, how='all')
            
            # Remove rows where key fields contain only whitespace or generic values
            for col in existing_key_fields:
                df = df[~df[col].astype(str).str.strip().isin(['', 'none', 'n/a', 'null', '-', 'na'])]
        
        return df
    
    df = clean_salesforce_csv(df)

    st.subheader("Accounts")
    st.dataframe(df)

    st.subheader("Basic Insights")

    st.write("Total Accounts:", len(df))

    if "Industry" in df.columns:
        st.bar_chart(df["Industry"].value_counts())

    def score_account(row):
        score = 0
        reasons = []
        leandata_angle = "Standard lead routing"
        signal_type = "General Growth Signal"
        persona = "Sales Leadership"
        competitive_opportunity = "No competitive opportunity detected"

        row_text = str(row).lower()

        # Cybersecurity keywords (highest priority - 40 points)
        cyber_keywords = ["cyber", "security", "threat", "vulnerability", "malware", "ransomware", "phishing", "zero trust", "identity", "compliance"]
        for keyword in cyber_keywords:
            if keyword in row_text:
                score += 40
                reasons.append("Cybersecurity focus")
                leandata_angle = "Routing governance, speed-to-lead"
                signal_type = "Cybersecurity GTM Complexity"
                persona = "RevOps / SDR Leadership"
                break

        # AI/ML keywords (35 points)
        ai_keywords = ["ai", "artificial intelligence", "machine learning", "ml", "deep learning", "neural network", "nlp", "generative", "llm", "chatbot"]
        for keyword in ai_keywords:
            if keyword in row_text:
                score += 35
                reasons.append("AI/ML technology")
                leandata_angle = "GTM orchestration complexity"
                signal_type = "AI Scale Expansion"
                persona = "Revenue Operations"
                break

        # SaaS keywords (30 points)
        saas_keywords = ["saas", "software as a service", "cloud", "subscription", "platform", "api", "integration"]
        for keyword in saas_keywords:
            if keyword in row_text:
                score += 30
                reasons.append("SaaS business model")
                leandata_angle = "Inbound volume management"
                signal_type = "Multi-Segment Routing Complexity"
                persona = "RevOps"
                break

        # Enterprise keywords (25 points)
        enterprise_keywords = ["enterprise", "b2b", "business", "corporate", "fortune", "large scale", "scalable"]
        for keyword in enterprise_keywords:
            if keyword in row_text:
                score += 25
                reasons.append("Enterprise focus")
                leandata_angle = "Territory management + SLA enforcement"
                signal_type = "Multi-Segment Routing Complexity"
                persona = "RevOps"
                break

        # Fintech keywords (20 points)
        fintech_keywords = ["fintech", "financial", "banking", "payments", "trading", "investment", "crypto"]
        for keyword in fintech_keywords:
            if keyword in row_text:
                score += 20
                reasons.append("Fintech sector")
                leandata_angle = "Compliance routing, deal speed"
                signal_type = "Compliance-Sensitive Growth"
                persona = "Marketing Ops"
                break

        # GTM Maturity Scoring - Crossbeam ecosystem/tools (30 points)
        gtm_tools = ["6sense", "drift", "salesloft", "demandbase", "cognism", "outreach", "marketo", "sfdc", "salesforce"]
        gtm_tools_found = []
        
        # Check Crossbeam column specifically
        crossbeam_col = None
        for col in row.index:
            if "crossbeam" in col.lower() or "ecosystem" in col.lower() or "tools" in col.lower():
                crossbeam_col = col
                break
        
        if crossbeam_col and pd.notna(row[crossbeam_col]):
            crossbeam_text = str(row[crossbeam_col]).lower()
            for tool in gtm_tools:
                if tool in crossbeam_text:
                    gtm_tools_found.append(tool)
        
        if gtm_tools_found:
            score += 30
            reasons.append(f"High GTM stack maturity ({', '.join(gtm_tools_found)})")
            competitive_opportunity = "High GTM stack maturity"

        # Competitive Opportunity Scoring - Bluebirds competitors (35 points)
        competitors = ["ringlead", "ring lead", "chili piper", "calendly", "routing"]
        competitor_found = None
        
        # Check Bluebirds - Competitors column specifically
        competitors_col = None
        for col in row.index:
            if "bluebirds" in col.lower() and "competitor" in col.lower():
                competitors_col = col
                break
        
        if competitors_col and pd.notna(row[competitors_col]):
            competitors_text = str(row[competitors_col]).lower()
            for competitor in competitors:
                if competitor in competitors_text:
                    competitor_found = competitor
                    break
        
        if competitor_found:
            score += 35
            if "ringlead" in competitor_found or "ring lead" in competitor_found:
                competitive_opportunity = "RingLead replacement opportunity"
            elif "chili piper" in competitor_found:
                competitive_opportunity = "Chili Piper coexistence opportunity"
            elif "calendly" in competitor_found:
                competitive_opportunity = "Calendly integration opportunity"
            else:
                competitive_opportunity = "Routing competitor displacement"

        # Generate outbound draft
        account_name = "your company"
        for col in ["Account Name", "Company", "Name", "Account"]:
            if col in row.index:
                account_name = str(row[col])
                break
        
        # Detect technically mature accounts for strategic positioning
        is_technically_mature = False
        tech_mature_keywords = ["data", "infrastructure", "devtools", "developer", "api", "platform", "engineering", "ml ops", "mlops", "data pipeline", "etl", "warehouse"]
        for keyword in tech_mature_keywords:
            if keyword in row_text:
                is_technically_mature = True
                break
        
        # Also consider accounts with mature GTM tooling as technically mature
        if gtm_tools_found:
            is_technically_mature = True
        
        # Helper function to capitalize tool names properly
        def capitalize_tools(text):
            tool_map = {
                "drift": "Drift",
                "salesloft": "Salesloft",
                "cognism": "Cognism",
                "6sense": "6sense",
                "marketo": "Marketo",
                "salesforce": "Salesforce",
                "sfdc": "Salesforce",
                "ringlead": "RingLead",
                "ring lead": "RingLead",
                "chili piper": "Chili Piper",
                "outreach": "Outreach",
                "demandbase": "Demandbase",
                "databricks": "Databricks",
                "openai": "OpenAI",
                "nvidia": "NVIDIA",
                "anthropic": "Anthropic",
                "n8n": "n8n",
                "google": "Google"
            }
            for lower, proper in tool_map.items():
                text = text.replace(lower, proper)
            return text
        
        # Capitalize GTM tools found
        gtm_tools_proper = [capitalize_tools(tool) for tool in gtm_tools_found]
        
        # Apply capitalization to reasons text (Why This Account Matters)
        reasons_text = capitalize_tools("; ".join(reasons) if reasons else "General account")
        
        # Apply capitalization to competitive opportunity
        competitive_opportunity = capitalize_tools(competitive_opportunity)
        
        # Strategic positioning narrative for technically mature accounts
        strategic_positioning = ""
        if is_technically_mature:
            strategic_positioning = "While many teams initially know LeanData for routing and matching, we're increasingly seeing leading AI-native organizations leverage us as a deterministic orchestration layer for coordinating AI-driven GTM signals and workflows.\n\n"
            strategic_positioning += "Companies like NVIDIA, Databricks, Anthropic, OpenAI, Google, n8n, and many Forbes Cloud 100 companies are using us for operational governance across their GTM motions.\n\n"
        
        # Contextual outbound based on competitive opportunity
        if "RingLead" in competitive_opportunity:
            # Market-observation language for RingLead
            observation = f"Hi {account_name},\n\nNoticed your {reasons_text} and {signal_type}."
            
            market_narrative = "We've been hearing more conversations lately around teams reassessing or rightsizing legacy lead management contracts as GTM organizations push for more orchestration visibility and flexibility."
            
            # Add GTM stack complexity context if applicable
            if gtm_tools_found:
                market_narrative += f"\n\nGiven your broader GTM stack ({', '.join(gtm_tools_proper)}), this level of complexity suggests routing, matching, and ownership governance are worth revisiting."
            
            # LeanData positioning
            positioning = strategic_positioning if is_technically_mature else ""
            
            # Soft CTA
            cta = f"I'd love to explore how LeanData could help your {persona} team with {leandata_angle}."
            
            # Combine sections
            outbound_draft = f"{observation}\n\n{market_narrative}\n\n{positioning}{cta}"
            
        elif "replacement" in competitive_opportunity or "displacement" in competitive_opportunity:
            observation = f"Hi {account_name},\n\nNoticed your {reasons_text} and {signal_type}."
            market_narrative = f"With {competitive_opportunity}, LeanData could help your {persona} team replace legacy systems and improve {leandata_angle}."
            positioning = strategic_positioning if is_technically_mature else ""
            cta = "Open to a brief conversation?"
            outbound_draft = f"{observation}\n\n{market_narrative}\n\n{positioning}{cta}"
            
        elif "coexistence" in competitive_opportunity or "integration" in competitive_opportunity:
            observation = f"Hi {account_name},\n\nNoticed your {reasons_text} and {signal_type}."
            market_narrative = f"With {competitive_opportunity}, LeanData can complement your existing stack and optimize {leandata_angle}."
            positioning = strategic_positioning if is_technically_mature else ""
            cta = "Open to a brief conversation?"
            outbound_draft = f"{observation}\n\n{market_narrative}\n\n{positioning}{cta}"
            
        else:
            observation = f"Hi {account_name},\n\nNoticed your {reasons_text} and {signal_type}."
            positioning = strategic_positioning if is_technically_mature else ""
            market_narrative = f"With {leandata_angle}, I'd love to explore how LeanData can help your {persona} team streamline operations and accelerate revenue."
            outbound_draft = f"{observation}\n\n{positioning}{market_narrative}"

        return score, reasons_text, leandata_angle, signal_type, persona, outbound_draft, competitive_opportunity

    # Apply scoring function and create all seven columns
    df[["LeanData Fit Score", "Why This Account Matters", "Suggested LeanData Angle", "Signal Type", "Recommended Persona", "Outbound Draft", "Competitive Opportunity"]] = df.apply(
        lambda row: pd.Series(score_account(row)), 
        axis=1
    )

    # Sort by score (highest first)
    df = df.sort_values("LeanData Fit Score", ascending=False)

    # Add helper columns for filtering
    df["Has Competitor"] = df["Competitive Opportunity"] != "No competitive opportunity detected"
    df["Is AI/Data"] = df["Why This Account Matters"].str.contains("AI/ML|data", case=False, na=False)
    df["Is Cybersecurity"] = df["Why This Account Matters"].str.contains("Cybersecurity", case=False, na=False)
    df["Has High GTM Maturity"] = df["Why This Account Matters"].str.contains("GTM stack maturity", case=False, na=False)

    # Territory Control Panel
    st.sidebar.header("🎯 Territory Control Panel")

    # Filters Section
    st.sidebar.subheader("🔍 Filters")

    # Industry filter
    if "Industry" in df.columns:
        industries = df["Industry"].unique()
        selected_industries = st.sidebar.multiselect(
            "Filter by Industry",
            options=industries,
            default=industries
        )
        df = df[df["Industry"].isin(selected_industries)]

    # Billing State filter
    if "Billing State" in df.columns:
        states = df["Billing State"].unique()
        selected_states = st.sidebar.multiselect(
            "Filter by Billing State",
            options=states,
            default=states
        )
        df = df[df["Billing State"].isin(selected_states)]

    # Minimum LeanData Fit Score filter
    min_score = st.sidebar.slider(
        "Minimum LeanData Fit Score",
        min_value=0,
        max_value=int(df["LeanData Fit Score"].max()),
        value=0,
        step=5
    )
    df = df[df["LeanData Fit Score"] >= min_score]

    # New checkbox filters
    show_competitors_only = st.sidebar.checkbox("Competitor present only", value=False)
    if show_competitors_only:
        df = df[df["Has Competitor"]]

    show_ai_only = st.sidebar.checkbox("AI/Data companies only", value=False)
    if show_ai_only:
        df = df[df["Is AI/Data"]]

    show_cyber_only = st.sidebar.checkbox("Cybersecurity companies only", value=False)
    if show_cyber_only:
        df = df[df["Is Cybersecurity"]]

    show_gtm_only = st.sidebar.checkbox("High GTM maturity only", value=False)
    if show_gtm_only:
        df = df[df["Has High GTM Maturity"]]

    # Territory Insights Section
    st.sidebar.subheader("📊 Territory Insights")
    
    total_accounts = len(df)
    competitor_accounts = df["Has Competitor"].sum()
    ai_accounts = df["Is AI/Data"].sum()
    cyber_accounts = df["Is Cybersecurity"].sum()
    gtm_accounts = df["Has High GTM Maturity"].sum()
    
    st.sidebar.metric("Total Accounts", total_accounts)
    st.sidebar.metric("Competitor Present", competitor_accounts)
    st.sidebar.metric("AI/Data Signals", ai_accounts)
    st.sidebar.metric("Cybersecurity", cyber_accounts)
    st.sidebar.metric("High GTM Maturity", gtm_accounts)

    # Top Industries
    if "Industry" in df.columns:
        st.sidebar.write("**Top Industries:**")
        top_industries = df["Industry"].value_counts().head(3)
        for industry, count in top_industries.items():
            st.sidebar.write(f"• {industry}: {count}")

    # Daily Priorities Section
    st.sidebar.subheader("🏆 Daily Priorities")
    
    top_5 = df.head(5)
    for index, row in top_5.iterrows():
        account_name = "Unknown"
        for col in ["Account Name", "Company", "Name", "Account"]:
            if col in df.columns:
                account_name = str(row[col])
                break
        
        score_color = "🟢" if row["LeanData Fit Score"] >= 80 else "🟡" if row["LeanData Fit Score"] >= 50 else "🔴"
        st.sidebar.write(f"{score_color} **{account_name}**")
        st.sidebar.write(f"Score: {row['LeanData Fit Score']}")
        st.sidebar.write(f"Persona: {row['Recommended Persona']}")
        st.sidebar.write("---")

    # Color-coded score styling function
    def color_score(val):
        if val >= 80:
            return 'background-color: #d4edda; color: #155724'  # Green
        elif val >= 50:
            return 'background-color: #fff3cd; color: #856404'  # Yellow
        else:
            return 'background-color: #f8d7da; color: #721c24'  # Red

    # Top 10 Priority Accounts Section
    st.subheader("🏆 Top 10 Priority Accounts")
    top_10 = df.head(10).copy()
    
    # Apply styling to top 10
    styled_top_10 = top_10.style.map(
        lambda x: color_score(x) if isinstance(x, (int, float)) and x == x else '',
        subset=["LeanData Fit Score"]
    )
    st.dataframe(styled_top_10, use_container_width=True)

    st.subheader("📊 All Scored Accounts (Sorted by Fit Score)")
    
    # Apply styling to all accounts
    styled_df = df.style.map(
        lambda x: color_score(x) if isinstance(x, (int, float)) and x == x else '',
        subset=["LeanData Fit Score"]
    )
    st.dataframe(styled_df, use_container_width=True)

    # Score distribution insights
    st.subheader("📈 Score Distribution")
    st.write(f"Highest Score: {df['LeanData Fit Score'].max()}")
    st.write(f"Average Score: {df['LeanData Fit Score'].mean():.1f}")
    st.write(f"Accounts with Score ≥ 50: {len(df[df['LeanData Fit Score'] >= 50])}")

    # Outbound Drafts Section
    st.subheader("✉️ Outbound Drafts")
    
    for index, row in df.iterrows():
        # Get account name from common columns
        account_name = "Unknown Account"
        for col in ["Account Name", "Company", "Name", "Account"]:
            if col in df.columns:
                account_name = str(row[col])
                break
        
        st.markdown(f"### {account_name}")
        st.markdown(f"**Target Persona:** {row['Recommended Persona']}")
        st.markdown(f"**Draft:** {row['Outbound Draft']}")
        st.markdown("---")